# Generated by Django 5.2.8 on 2025-11-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(max_length=255, verbose_name='Nome da Clínica')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('num_fisioterapeutas', models.IntegerField(default=1, help_text='Quantidade estimada de profissionais que usarão o sistema', verbose_name='Número de Fisioterapeutas')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('NOVO', 'Novo Lead'), ('CONTATO', 'Em Contato'), ('DEMONSTRACAO', 'Demonstração Agendada'), ('PROPOSTA', 'Proposta Enviada'), ('CONVERTIDO', 'Convertido em Cliente'), ('PERDIDO', 'Lead Perdido')], default='NOVO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('notas', models.TextField(blank=True, help_text='Observações da equipe Core Hive', verbose_name='Notas Internas')),
                ('clinica_convertida', models.ForeignKey(blank=True, help_text='Preenchido quando o lead se torna cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='authentication.clinica', verbose_name='Clínica Convertida')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
