# Generated by Django 5.2.8 on 2025-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('GESTOR', 'Gestor da Clínica'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('ATENDENTE', 'Atendente/Recepção')], default='FISIOTERAPEUTA', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
