# Generated by Django 5.2.8 on 2025-11-05 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CONSULTA', 'Consulta'), ('AVALIACAO', 'Avaliação'), ('EVOLUCAO', 'Evolução'), ('PROCEDIMENTO', 'Procedimento'), ('EXAME', 'Exame'), ('DIAGNOSTICO', 'Diagnóstico'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Registro')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('chief_complaint', models.TextField(blank=True, null=True, verbose_name='Queixa Principal')),
                ('history', models.TextField(blank=True, null=True, verbose_name='História')),
                ('physical_exam', models.TextField(blank=True, null=True, verbose_name='Exame Físico')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='Plano de Tratamento')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_modified', to=settings.AUTH_USER_MODEL, verbose_name='Última modificação por')),
            ],
            options={
                'verbose_name': 'Prontuário Médico',
                'verbose_name_plural': 'Prontuários Médicos',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão')], max_length=10, verbose_name='Ação')),
                ('previous_data', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='Campos Alterados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='prontuario.medicalrecord', verbose_name='Prontuário')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Prontuário',
                'verbose_name_plural': 'Históricos de Prontuários',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='Medicações em Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='prontuario.patient', verbose_name='Paciente'),
        ),
    ]
