# Generated by Django 5.2.8 on 2025-12-08 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_user_type'),
        ('prontuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Plano')),
                ('objectives', models.TextField(verbose_name='Objetivos do Tratamento')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico Fisioterapêutico')),
                ('total_sessions', models.IntegerField(verbose_name='Total de Sessões Planejadas')),
                ('frequency', models.CharField(choices=[('1x_semana', '1x por semana'), ('2x_semana', '2x por semana'), ('3x_semana', '3x por semana'), ('4x_semana', '4x por semana'), ('5x_semana', '5x por semana'), ('diario', 'Diário'), ('sob_demanda', 'Sob demanda')], default='2x_semana', max_length=20, verbose_name='Frequência')),
                ('session_duration_minutes', models.IntegerField(default=50, verbose_name='Duração por Sessão (min)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Previsão de Término')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término Real')),
                ('observations', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='authentication.clinica', verbose_name='Clínica')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta Responsável')),
                ('initial_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='prontuario.medicalrecord', verbose_name='Avaliação Inicial')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='prontuario.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Plano de Tratamento',
                'verbose_name_plural': 'Planos de Tratamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Data Agendada')),
                ('scheduled_time', models.TimeField(verbose_name='Horário Agendado')),
                ('duration_minutes', models.IntegerField(default=50, verbose_name='Duração (minutos)')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('EM_ANDAMENTO', 'Em Andamento'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('FALTA', 'Falta do Paciente'), ('REMARCADA', 'Remarcada')], default='AGENDADA', max_length=20, verbose_name='Status')),
                ('session_number', models.IntegerField(blank=True, null=True, verbose_name='Número da Sessão')),
                ('procedures', models.TextField(blank=True, verbose_name='Procedimentos Realizados')),
                ('evolution', models.TextField(blank=True, verbose_name='Evolução do Quadro')),
                ('pain_scale_before', models.IntegerField(blank=True, null=True, verbose_name='Escala de Dor (Antes)')),
                ('pain_scale_after', models.IntegerField(blank=True, null=True, verbose_name='Escala de Dor (Depois)')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Início Real')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Término Real')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.clinica', verbose_name='Clínica')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_as_therapist', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='prontuario.patient', verbose_name='Paciente')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='prontuario.treatmentplan', verbose_name='Plano de Tratamento')),
            ],
            options={
                'verbose_name': 'Sessão de Fisioterapia',
                'verbose_name_plural': 'Sessões de Fisioterapia',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MELHORA', 'Alta por Melhora'), ('CURA', 'Alta por Cura'), ('ABANDONO', 'Abandono do Tratamento'), ('ENCAMINHAMENTO', 'Encaminhamento para Outro Profissional'), ('TRANSFERENCIA', 'Transferência de Clínica'), ('OBITO', 'Óbito'), ('OUTRO', 'Outro Motivo')], max_length=20, verbose_name='Motivo da Alta')),
                ('reason_details', models.TextField(blank=True, verbose_name='Detalhes do Motivo')),
                ('discharge_date', models.DateField(verbose_name='Data da Alta')),
                ('final_evaluation', models.TextField(verbose_name='Avaliação Final')),
                ('initial_condition', models.TextField(blank=True, verbose_name='Condição Inicial')),
                ('final_condition', models.TextField(blank=True, verbose_name='Condição Final')),
                ('treatment_summary', models.TextField(blank=True, verbose_name='Resumo do Tratamento')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendações ao Paciente')),
                ('follow_up_instructions', models.TextField(blank=True, verbose_name='Instruções de Acompanhamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='authentication.clinica', verbose_name='Clínica')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharges_given', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta Responsável')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharges', to='prontuario.patient', verbose_name='Paciente')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='prontuario.treatmentplan', verbose_name='Plano de Tratamento')),
            ],
            options={
                'verbose_name': 'Alta/Encerramento',
                'verbose_name_plural': 'Altas/Encerramentos',
                'ordering': ['-discharge_date'],
            },
        ),
    ]
