# Generated by Django 5.2.8 on 2025-12-10 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('prontuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Explique o motivo da solicitação de transferência', verbose_name='Motivo da Transferência')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('response_note', models.TextField(blank=True, null=True, verbose_name='Observação do Gestor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analisado em')),
                ('from_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_out', to='authentication.filial', verbose_name='Filial de Origem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='prontuario.patient', verbose_name='Paciente')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
                ('to_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_in', to='authentication.filial', verbose_name='Filial de Destino')),
                ('to_fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta de Destino')),
            ],
            options={
                'verbose_name': 'Solicitação de Transferência',
                'verbose_name_plural': 'Solicitações de Transferência',
                'ordering': ['-created_at'],
            },
        ),
    ]
