# Generated by Django 5.2.8 on 2025-12-10 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0002_transferrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fisioterapeuta',
            field=models.ForeignKey(blank=True, help_text='Fisioterapeuta atualmente responsável por este paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meus_pacientes', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta Responsável'),
        ),
    ]
