# Generated by Django 5.2.8 on 2025-12-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prontuario', '0003_patient_fisioterapeuta_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1, verbose_name='Gênero'),
        ),
    ]
