# Generated by Django 5.2.8 on 2025-12-08 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_user_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='authentication.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Categoria de Estoque',
                'verbose_name_plural': 'Categorias de Estoque',
                'ordering': ['name'],
                'unique_together': {('clinica', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU/Código')),
                ('item_type', models.CharField(choices=[('MATERIAL', 'Material'), ('INSUMO', 'Insumo'), ('EQUIPAMENTO', 'Equipamento'), ('MEDICACAO', 'Medicação'), ('DESCARTAVEL', 'Descartável'), ('OUTRO', 'Outro')], default='MATERIAL', max_length=20, verbose_name='Tipo')),
                ('unit', models.CharField(choices=[('unidade', 'Unidade(s)'), ('par', 'Par(es)'), ('caixa', 'Caixa(s)'), ('pacote', 'Pacote(s)'), ('rolo', 'Rolo(s)'), ('metro', 'Metro(s)'), ('ml', 'mL'), ('litro', 'Litro(s)'), ('kg', 'Kg'), ('grama', 'Grama(s)')], default='unidade', max_length=20, verbose_name='Unidade de Medida')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Atual')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Mínima (Alerta)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo por Unidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='estoque.inventorycategory', verbose_name='Categoria')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='authentication.clinica', verbose_name='Clínica')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE_MAIS', 'Ajuste (+)'), ('AJUSTE_MENOS', 'Ajuste (-)'), ('PERDA', 'Perda/Extravio'), ('VENCIMENTO', 'Vencimento')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Antes')),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Depois')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência/NF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='estoque.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
