# Generated by Django 5.2.8 on 2025-11-06 03:44

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prontuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Imagem'), ('DOC', 'Documento Word'), ('EXCEL', 'Planilha Excel'), ('FICHA', 'Ficha de Avaliação'), ('EXAME', 'Exame'), ('ATESTADO', 'Atestado'), ('RECEITA', 'Receita'), ('OTHER', 'Outro')], max_length=10, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to=documentos.models.document_upload_path, verbose_name='Arquivo')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensão')),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído (OCR)')),
                ('ocr_confidence', models.FloatField(blank=True, null=True, verbose_name='Confiança do OCR (%)')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='OCR Processado')),
                ('ocr_language', models.CharField(default='por', max_length=10, verbose_name='Idioma OCR')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/', verbose_name='Miniatura')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Público'), ('RESTRICTED', 'Restrito'), ('CONFIDENTIAL', 'Confidencial')], default='RESTRICTED', max_length=15, verbose_name='Nível de Acesso')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Data do Documento')),
                ('tags', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tags (separadas por vírgula)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_modified', to=settings.AUTH_USER_MODEL, verbose_name='Última modificação por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prontuario.patient', verbose_name='Paciente')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documentos.documentcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Visualização'), ('DOWNLOAD', 'Download'), ('EDIT', 'Edição'), ('DELETE', 'Exclusão')], max_length=10, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Detalhes')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documentos.document', verbose_name='Documento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso a Documento',
                'verbose_name_plural': 'Logs de Acesso a Documentos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
