# Generated by Django 5.2.8 on 2025-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiança do OCR (%)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_language',
            field=models.CharField(default='por', max_length=10, verbose_name='Idioma OCR'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_processed',
            field=models.BooleanField(default=False, verbose_name='OCR Processado'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Extraído (OCR)'),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Imagem'), ('DOC', 'Documento Word'), ('EXCEL', 'Planilha Excel'), ('FICHA', 'Ficha de Avaliação'), ('EXAME', 'Exame'), ('ATESTADO', 'Atestado'), ('RECEITA', 'Receita'), ('OTHER', 'Outro')], max_length=10, verbose_name='Tipo de Documento'),
        ),
    ]
