# Generated by Django 5.2.8 on 2025-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_administrative',
            field=models.BooleanField(default=False, help_text='Se marcado, atendentes podem visualizar este documento', verbose_name='Documento Administrativo'),
        ),
    ]
